GET https://cloudfunctionapp-djcgaka2bfamf8bj.italynorth-01.azurewebsites.net/api/hello/world

###

GET https://cloudfunctionapp-djcgaka2bfamf8bj.italynorth-01.azurewebsites.net/api/calculator/3/5


###
GET http://localhost:7071/api/calculator/3/5/subtract

